config/routes.rb
SampleApp::Application.routes.draw do
  get "streamings/new"
  get "tweets/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :searches
  resources :searchruns, only: [:create, :destroy]
  resources :streamings
  resources :streamingruns, only: [:create, :destroy]
  resources :credentials
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @search = current_user.searches.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
 
  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<h3>Historical search</h3>
<p>
  The historical search allows you to use a number of different operators to 
  help refine your search.
</p>
<p>
  Remember that this kind of search only always querying from the past and is 
  limited by the twitter search API to retrieving tweets from the last 7 days 
  only. 
  <%= link_to "More info", "https://dev.twitter.com/docs/faq#8650" %> 
</p>
<ol class="searches">
  <table class="table">
    <thead>
      <tr>
        <th>Operation</th>
        <th>Results Returned</th>
      <tr>
    </thead>
    <tbody>
      <tr>
        <td>twitter search</td>
        <td>Returns all tweets containing both "twitter" and "search"</td>
      </tr>
      <tr>
        <td>twitter AND search</td>
        <td>Returns all tweets containing both "twitter" and "search"</td>
      </tr>  
      <tr>
        <td>"happy hour"</td>
        <td>Returns all tweets which containing the exact phrase "happy hour"</td>
      </tr>
      <tr>
        <td>love OR hate</td>
        <td>Returns all tweets containing either "love" or "hate" (or both)</td>
      </tr>
      <tr>
        <td>beer -root</td>
        <td>Returns all tweets containing "beer" but not "root"</td>
      </tr>
      <tr>
        <td>#haiku</td>
        <td>Returns all tweets containing the hashtag "haiku"</td>
      </tr>
      <tr>
        <td>from:user</td>
        <td>Returns all tweets sent from the user @user</td>
      </tr>
      <tr>
        <td>to:user</td>
        <td>Returns all tweets sent to the user @user</td>
      </tr>
      <tr>
        <td>@user</td>
        <td>Returns all tweets mentioning @user</td>
      </tr>
    </tbody>
  </table>
</ol>
<br>
<br>
<h3>Streaming search</h3>
<p>
  The streaming search only allows you to enter keywords or phrases separated by 
  commas. Here the spaces operate like logical ANDs and the commas like logical 
  ORs.
</p>
<ol class="searches">
  <table class="table">
    <thead>
      <tr>
        <th>Operation</th>
        <th>Results Returned</th>
      <tr>
    </thead>
    <tbody>
      <tr>
        <td>twitter search</td>
        <td>Returns all tweets containing both "twitter" and "search"</td>
      </tr>
      <tr>
        <td>love, hate</td>
        <td>Returns all tweets containing either "love" or "hate" (or both)</td>
      </tr>
    </tbody>
  </table>
</ol>
<br>
<br>
<p>
  The text of the Tweet and some entity fields are considered for matches.  
  Specifically, the <tt>text</tt> attribute of the Tweet, <tt>expanded_url</tt> 
  and <tt>display_url</tt> for links and media, <tt>text</tt> for hashtags, and 
  <tt>screen_name</tt> for user mentions are checked for matches.
</p>
<p>
  Each phrase must be between 1 and 60 bytes, inclusive.
</p>
<p>
  Exact matching of phrases (equivalent to quoted phrases in most search 
  engines) is not supported.
</p>
<p>
  Punctuation and special characters will be considered part of the term they 
  are adjacent to.  In this sense, "hello." is a different track term than 
  "hello".  However, matches will ignore punctuation present in the Tweet.  So 
  "hello" will match both "hello world" and "my brother says hello."  Note that 
  punctuation is not considered to be part of a #hashtag or @mention, so a track 
  term containing punctuation will not match either #hashtags or @mentions.
</p>
<p>
  UTF-8 characters will match exactly, even in cases where an "equivalent" ASCII 
  character exists.  For example, "touché" will not match a Tweet containing 
  "touche".
</p>
<p>
  Non-space separated languages, such as CJK and Arabic, are currently 
  unsupported.
</p>
<p>
  URLs are considered words for the purposes of matches which means that the 
  entire domain and path must be included in the track query for a Tweet 
  containing an URL to match.  Note that <tt>display_url</tt> does not contain a 
  protocol, so this is not required to perform a match.
</p>
<p>
  Twitter currently canonicalizes the domain "www.example.com" to "example.com" 
  before the match is performed, so omit the "www" from URL track terms.
</p>
<p>
  If you need more help 
  <%= link_to "see this", "https://dev.twitter.com/docs/streaming-apis/keyword-matching" %>
</p>
<p>Track examples:</p>
<table class="table">
  <thead>
    <tr>
      <th>Parameter value</th><th>Will match...</th><th>Will not match...</th>
    </tr>
  <thead>
  <tr>
    <td>Twitter</td>
    <td>TWITTER
      <br>twitter
      <br>"Twitter"
      <br>twitter.
      <br>#twitter
      <br>@twitter
      <br>http://twitter.com
    </td>
    <td>
      TwitterTracker<br>#newtwitter
    </td>
  </tr>
  <tr>
    <td>Twitter's</td>
    <td>I like Twitter's new design</td>
    <td>Someday I'd like to visit @Twitter's office</td>
  </tr>
  <tr>
    <td>twitter api,twitter streaming</td>
    <td>The Twitter API is awesome
      <br>The twitter streaming service is fast
      <br>Twitter has a streaming API
    </td>
    <td>I'm new to Twitter</td>
  </tr>
  <tr>
    <td>example.com</td>
    <td>Someday I will visit example.com</td>
    <td>There is no example.com/foobarbaz</td>
  </tr>
  <tr>
    <td>example.com/foobarbaz</td>
    <td>example.com/foobarbaz
      <br>www.example.com/foobarbaz
    </td>
    <td>example.com</td>
  </tr>
  <tr>
    <td>www.example.com/foobarbaz</td>
    <td>.</td>
    <td>www.example.com/foobarbaz</td>
  </tr>
</table>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Welcome back to Quiltro</h3>
        <p>
          Quiltro allows you to collect tweets using a keyword or set of keywords. To use Quiltro you must first create a Twitter developer account. When you login to quiltro, enter your Twitter dev account details under the 'credentials' tab and then you're ready to start collecting tweets.
        </p>
        <p>
          Once you're set up you can create multiple searches, each of which will collect and save tweets for you directly from the twitter APIs. Quiltro is a valuable tool for anyone searching for tweets regarding specific topics on twitter and can be useful to collect samples for further analysis.
        </p>
        <p>
          Users can carry out two types of search - streaming and historical. The streaming search will return tweets featuring the keywords in real time starting from the moment the search is begun. This returns results from Twitter's streaming API. The historical search returns results from the Twitter search API. This allows users to collect tweets from any time in the previous week, but will not continue to collect future tweets.
        </p>
        <h4> Start collecting tweets </h4>
        <p>  
          <%= link_to "Historical search", searches_path(current_user) %>
          <br> 
          <%= link_to "Streaming search", streamings_path(current_user) %>
        </p>
      <br>
      <br>
      <h3>Recent news </h3>
        <h4> Quiltro beta version is running </h4>
        <p> 
          The beta version of Quiltro is now active. You can use it as you want. However, this version is still preliminar and probably you can found bugs out there. If you find some one, please report it here.
        </p> 
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to Quiltro</h1>
    <%= image_tag("quiltro.jpg", alt: "quiltro") %>
    <h4>
      This app is developed by
      <a href="http://hujo.deri.ie/">Digital Humanities and Journalism</a>
      working group at DERI.
    </h4>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>