config/routes.rb
SampleApp::Application.routes.draw do
  get "streamings/new"
  get "tweets/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :searches
  resources :searchruns, only: [:create, :destroy]
  resources :streamings
  resources :streamingruns, only: [:create, :destroy]
  resources :credentials
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/views/shared/_credential_form.html.erb
<%= form_for(@credential) do |f| %>
  <p>
  To create new credentials please enter your Twitter developer account details
  below:
  </p>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.text_field :consumer, placeholder: "Consumer token" %>
    <%= f.text_field :consumer_secret, placeholder: "Consumer secret" %>
    <%= f.text_field :access, placeholder: "Access token" %>
    <%= f.text_field :access_secret, placeholder: "Access token secret" %>
  </div>
  <%= f.submit "Add", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="searches">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="query"><%= feed_item.query %></span>
  <span class="timestamp">
    Started <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <span class="timestamp">
    Using credential <%= feed_item.credential.name %>.
  </span>
  <span class="timestamp">
    Type <%= feed_item.kind %>.
  </span>
  <span class="actions">
    Actions: 
    <% if current_user?(feed_item.user) %>
      <% if feed_item.get_searchrun %>
        <%= link_to "stop", searchrun_path(@searchrun, :id => feed_item.get_searchrun.id), :method => :delete %>
      <% else %>
        <%= link_to "start", searchruns_path(@searchrun, :search => feed_item.id), :method => :post %>
      <% end %>
      |
      <%= link_to "tweets", {:controller => "tweets", :action => "index", :search => feed_item.id, :kind => "search" } %>
      |
      <%= link_to "get data", {:controller => "searches", :action => "index", :id => feed_item.id } %>
      |
      <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     title: feed_item.query,
                                     remot: true, 
                                     class: "alert" %>
    <% end %>
  </span>
</li>

app/views/shared/_search_form.html.erb
<%= form_for(@search) do |f| %>>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    Need help for query? 
    <%= link_to "Look here", help_path %>
    <%= f.text_area :query, placeholder: "Compose new search... " %>
    <% if Credential.find_by_user_id(current_user.id).nil? %>
      Please add credential first
    <% else %>
      <%= collection_select(:search, :credential_id, Credential.where(user_id: current_user.id), :id, :name, :prompt => true) %>
    <% end %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_search_links.html.erb
<% if defined? @searches %>
  <%= link_to "Historical Search", searches_path(current_user), class: "btn btn-small disabled" %>
  <%= link_to "Streaming Search", streamings_path(current_user), class: "btn btn-small" %>
<% else %>
  <%= link_to "Historical Search", searches_path(current_user), class: "btn btn-small" %>
  <%= link_to "Streaming Search", streamings_path(current_user), class: "btn btn-small disabled" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 65 %>
</a>
<h1>
  <% current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.searches.count, "historical search") %>
</span>
<span>
  <%= pluralize(current_user.streamings.count, "streaming search") %>
</span>
<span>
  <%= pluralize(current_user.credentials.count, "credential") %>
</span>