config/routes.rb
SampleApp::Application.routes.draw do
  get "streamings/new"
  get "tweets/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :searches
  resources :searchruns, only: [:create, :destroy]
  resources :streamings
  resources :streamingruns, only: [:create, :destroy]
  resources :credentials
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/models/streaming.rb
require 'active_resource'

class Streaming < ActiveRecord::Base
  belongs_to :user
  belongs_to :credential
  default_scope -> { order('created_at DESC') }
  validates :query, presence: true, length: { maximum:140 }
  validates :credential_id, presence: true
  validates :user_id, presence: true

  def tweets
    #This method only retreive the last ten tweets
    @collection = Tweet.find(:all, :params => {:streaming_id => id, :last => 1})
  end

  def all_tweets
    #Get all tweets for this collection
    @collection = Tweet.find(:all, :params => {:streaming_id => id })
  end

  def get_streamingrun
    Streamingrun.find(:first, :params => {:streaming_id => id })
  end

end

app/controllers/streamings_controller.rb
class StreamingsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :index]
  before_action :correct_user, only: [:destroy]

  def index
    @streaming = current_user.streamings.build
    @streamings = current_user.streamings.paginate(page: params[:page])
  end

  def create
    @streaming = current_user.streamings.build(streaming_params)
    if @streaming.save
      @streamingrest = fill_streamingrest(@streaming)
      if @streamingrest.save
        flash[:success] = "Streaming created!"
        redirect_to streamings_path
      else
        @streaming.destroy
        #is this line correct? original: @feed_items = []
        @feed_items = current_user.feed.paginate(page: params[:page])
        render 'index'
      end
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'index'
    end
  end

  def destroy
    @streaming.destroy
    @streamingrest = find_streamingrest(@streaming.id)
    if not @streamingrest.blank?
      @streamingrest.destroy
    end
    redirect_to streamings_path
  end

  private
    def streaming_params
      params.require(:streaming).permit(:query, :credential_id)
    end

    def correct_user
      @streaming = current_user.streamings.find_by(id: params[:id])
      redirect_to streamings_path if @streaming.nil?
    end

    def fill_streamingrest(streaming)
      if not streaming.credential.blank?
        streamingrest = Streamingrest.build()
        streamingrest.id = streaming.id
        streamingrest.query = streaming.query
        streamingrest.consumer = streaming.credential.consumer
        streamingrest.consumer_secret = streaming.credential.consumer_secret
        streamingrest.access = streaming.credential.access
        streamingrest.access_secret = streaming.credential.access_secret
        return streamingrest
      else
        return false
      end
    end

    def find_streamingrest(id)
      if Streamingrest.exists?(id)
        return Streamingrest.find(id)
      end
    end
end

app/helpers/streamings_helper.rb
module StreamingsHelper
end

app/views/streamings/_streaming.html.erb
<li>
  <span class="user">
    <%= link_to streaming.user.name, streaming.user %>
  </span>
  <span class="query"><%= streaming.query %></span>
  <span class="timestamp">
    Started <%= time_ago_in_words(streaming.created_at) %> ago.
  </span>
  <span class="timestamp">
    Using credential <%= streaming.credential.name %>.
  </span>
  <span class="actions">
    <% if current_user?(streaming.user) %>
      <% if streaming.get_streamingrun %>
        <%= link_to '<i class="icon-stop icon-black"></i>'.html_safe, streamingrun_path(@streamingrun, :id => streaming.get_streamingrun.id), :method => :delete, class: "btn btn-small", data: {toggle: "tooltip"}, title: "Stop tweets collection" %>
      <% else %>
        <%= link_to '<i class="icon-play icon-black"></i>'.html_safe, streamingruns_path(@streamingrun, :streaming => streaming.id), :method => :post, class: "btn btn-small", data: {toggle: "tooltip"}, title: "Start tweets collection" %>
      <% end %>
      <%= link_to '<i class="icon-eye-open icon-black"></i>'.html_safe, {:controller => "tweets", :action => "index", :streaming => streaming.id, :kind => "streaming"}, class: "btn btn-small", data: {toggle: "tooltip"}, title: "See last tweets retrieved" %>
      <%= link_to '<i class="icon-download icon-black"></i>'.html_safe, {:controller => "tweets", :action => "index", :streaming => streaming.id, :kind => "streaming", :format => :csv }, class: "btn btn-small", data: {toggle: "tooltip"}, title: "Download tweet collection" %>

      <!-- Button to trigger modal -->
      <a href="#modalStreaming" role="button" data-toggle="modal" class="btn btn-small btn-warning" title="Delete collection"> <i class="icon-trash icon-black"></i></a>

      <!-- Modal -->
      <div id="modalStreaming" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Delete collection</h3>
        </div>
        <div class="modal-body">
          <p>Are you sure you want delete streaming collection?</p>
        </div>
        <div class="modal-footer">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
          <%= link_to "Delete it", streaming, method: :delete, remot: true, class: "btn btn-small btn-warning" %>
        </div>
      </div> 
    <% end %>  
  </span>
</li>

app/views/streamings/_streaming_form.html.erb
<%= form_for(@streaming) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <br>
    Enter keyword search terms below. If using multiple keywords please enter a comma , between each keyword.
    <br>
    <br>Click 
    <%= link_to "here", help_path %>  for a more detailed help guide
    <br>
    <br> 
    <%= f.text_area :query, placeholder: "Compose new streaming search... " %>
    <% if Credential.find_by_user_id(current_user.id).nil? %>
      Please add credential first
    <% else %>
      <%= collection_select(:streaming, :credential_id, Credential.where(user_id: current_user.id), :id, :name, :prompt => 'Please select credentials') %>
    <% end %>
  </div>
  <%= f.submit "Search", class: "btn btn-large btn-primary" %>
<% end %>

app/views/streamings/index.html.erb
<% provide(:title, 'Streaming') %>
<h1>Streaming search</h1>
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/search_links' %>
    </section>
    <section>
      <%= render 'streaming_form' %>
    </section>
  </aside>
  <div class="span8">
    <p>
      The streaming search allows you to collect live tweets in real time. To retrieve streaming tweets simply enter some keywords in the search box below. This returns relevant tweets from the Twitter streaming API. The streaming search will return tweets starting from the time the search begins as they come in until you decide to stop the search.
    </p>
    <%= will_paginate %>
    <ol class="streamings">
      <%= render @streamings %>
    </ol>
    <%= will_paginate %>
  </div>
</div>