config/routes.rb
SampleApp::Application.routes.draw do
  get "streamings/new"
  get "tweets/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :searches
  resources :searchruns, only: [:create, :destroy]
  resources :streamings
  resources :streamingruns, only: [:create, :destroy]
  resources :credentials
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/views/layouts/_about_modal.html.erb
<!-- Modal -->
<div id="modalAbout" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalAboutLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="modalAboutLabel">About us</h3>
  </div>
  <div class="modal-body">
    <p>
      Create by Digital Humanities and Journalism working group at DERI in NUI Galway.
    </p>
    <p>
      Quiltro is a tool that allows you to collect tweets using a keyword or set of keywords. You can use Quiltro to keep a record of tweets about a certain subject or event or to build a dataset of tweets to use for analysis.
    </p>
    <p>
      To get started you must create a Twitter developer account which you can do <%= link_to "here", "https://dev.twitter.com/user/login" %>. Then register for a Quiltro account, enter your Twitter dev account details and you're ready to go! Once registered with an account you can create multiple searches, each of which will collect and save tweets for you directly from the twitter APIs.
    </p>
    <p>
      Quiltro is developed by the Digital Humanities and Journalism working group at DERI in NUI Galway. The  Digital Humanities and Journalism group is a multidisciplinary effort aiming to bundle research and development activities around news and journalism, media, digital humanities and social sciences with social media and semantic web technologies, which are DERI's core strengths. The groups collaborates media organisations and academic partners in the field to study, create, design, deploy, and assess tools and practices in Digital Humanities, media and journalism.
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Ok</button>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to image_tag("HUJO-DERI-SFI-NUI_Galway.jpg"), "http://hujo.deri.ie" %>
  </small>
  <nav>
    <ul>
      <li><!-- Button to trigger modal -->
        <a href="#modalAbout" data-toggle="modal">About</a>
      </li>
      <li><%= link_to "Contact", "http://hujo.deri.ie/contact" %></li>
      <li><%= link_to "Hujo", "http://hujo.deri.ie" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "quiltro", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li>
            <%= link_to root_path do %>
              <i class="icon-home icon-white"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to help_path do %>
              <i class="icon-question-sign icon-white"></i> Help
            <% end %>
          </li>
          <% if signed_in? %>
            <% if admin_user? %>
                <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-search icon-white"></i> 
                Search <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to searches_path(current_user) do %>
                    <i class="icon-book icon-black"></i> Historical
                  <% end %>
                </li>
                <li>
                  <%= link_to streamings_path(current_user) do %>
                    <i class="icon-refresh icon-black"></i> Streaming
                  <% end %>
                </li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user icon-white"></i> 
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <!-- <li><%= link_to "Profile", current_user %></li> -->
                <li>
                  <%= link_to edit_user_path(current_user) do %>
                    <i class="icon-edit icon-black"></i> Settings
                  <% end %>
                </li>
                <li>
                  <%= link_to credentials_path(current_user) do %>
                    <i class="icon-wrench icon-black"></i> Credentials
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to signout_path, method: "delete" do %>
                    <i class="icon-off icon-black"></i> Sign out
                  <% end %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/about_modal' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>